# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true

language: rust
rust:
  - stable
  - nightly

cache: cargo

branches:
  only:
  - master
  - marcel_travis

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS=" -W unused-extern-crates"

before_install:
  # Check how much space we've got on this machine.
  - df -h

script:
  - ./ci/setup.sh
  - ./ci/build.sh
  - ./ci/test.sh

after_script:
  # Check how much free disk space left after the build
  - df -h