[profile.release]
panic = "unwind"

[[bin]]
name = "substrate-test-node"
path = "src/main.rs"

[build-dependencies]
vergen = "3"

[package]
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"
edition = "2018"
name = "substrate-test-node"
version = "2.0.0"

[dependencies]
derive_more = "0.14.0"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1"
exit-future = "0.1"
parking_lot = "0.8.0"
parity-codec = "4.1.1"
trie-root = "0.14.0"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura-primitives"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
package = "substrate-basic-authorship"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.consensus]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
package = "substrate-inherents"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
package = "substrate-network"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.substrate-test-node-runtime]
path = "runtime"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
package = "substrate-transaction-pool"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"
