[profile.release]
panic = "unwind"

[[bin]]
name = "substrate-test-node"
path = "src/main.rs"

[build-dependencies]
vergen = "3"

[package]
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"
edition = "2018"
name = "substrate-test-node"
version = "2.0.0"

[dependencies]
derive_more = "0.14.0"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1"
exit-future = "0.1"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.0"

[dependencies.aura-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura-primitives"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
package = "substrate-basic-authorship"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.contracts]
git = "https://github.com/paritytech/substrate"
package = "srml-contracts"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.consensus]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.grandpa-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-finality-grandpa-primitives"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
package = "substrate-inherents"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
package = "substrate-network"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.test-node-runtime]
path = "runtime"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
package = "substrate-transaction-pool"
rev = "6d47fd919b4d86e4348c6c19d99c80372587d215"
