[package]
name = "test-node-runtime"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2" }

[dependencies.aura]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-aura"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.balances]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-balances"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.client]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-client"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.consensus-aura]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-aura-primitives"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.contracts]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-contracts"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.executive]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-executive"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.indices]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-indices"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.offchain-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-offchain-primitives"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "1.0.0"

[dependencies.primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.rstd]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-std"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.runtime-io]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-io"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.sr-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.safe-mix]
default-features = false
version = "1.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.substrate-session]
default-features = false
git = "https://github.com/paritytech/substrate"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.sudo]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-sudo"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-support"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-system"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.timestamp]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-timestamp"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[dependencies.version]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-version"
rev = "8b96ce62da9c88afbd13405396d1cc8588be67a5"

[features]
default = ["std"]
std = [
    "codec/std",
    "client/std",
    "contracts/std",
    "rstd/std",
    "runtime-io/std",
    "support/std",
    "balances/std",
    "executive/std",
    "aura/std",
    "indices/std",
    "primitives/std",
    "sr-primitives/std",
    "system/std",
    "timestamp/std",
    "sudo/std",
    "version/std",
    "serde",
    "safe-mix/std",
    "consensus-aura/std",
    "offchain-primitives/std",
]
no_std = [
    "contracts/core",
]
