[package]
name = "test-node-runtime"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"



[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.101"

[dependencies.safe-mix]
default-features = false
version = "1.0.0"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "1.0.0"

[dependencies.rstd]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-std"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.runtime-io]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-io"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.version]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-version"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-support"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.substrate-session]
default-features = false
git = "https://github.com/paritytech/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.balances]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-balances"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.babe]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-babe"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.babe-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-babe-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.executive]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-executive"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.indices]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-indices"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.grandpa]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-grandpa"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-system"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.timestamp]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-timestamp"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.sudo]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-sudo"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.sr-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.client]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-client"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.offchain-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-offchain-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.contracts]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-contracts"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"



[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2" }

[features]
default = ["std"]
std = [
	"codec/std",
	"client/std",
	"rstd/std",
	"runtime-io/std",
	"support/std",
	"balances/std",
	"babe/std",
	"babe-primitives/std",
	"executive/std",
	"indices/std",
	"grandpa/std",
	"primitives/std",
	"sr-primitives/std",
	"system/std",
	"timestamp/std",
	"sudo/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"offchain-primitives/std",
	"substrate-session/std",
    "contracts/std",
]
#no_std = [
#    "contracts/core",
#]
